"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultAccountantPermissions = exports.DefaultReadOnlyPermissions = exports.DefaultAdminPermissions = exports.DefaultPermissions = void 0;
exports.DefaultPermissions = [
    { permissionName: 'Dashboard', sortId: 1 },
    { permissionName: 'Roles', sortId: 7 },
    { permissionName: 'Users', sortId: 8 },
    { permissionName: 'Integrations', sortId: 9 },
    { permissionName: 'Subscriptions', sortId: 11 },
];
exports.DefaultAdminPermissions = [
    {
        permissionName: 'Dashboard',
        sortId: 1,
        all: true,
        view: true,
        edit: true,
        delete: true,
        add: true,
    },
    // {
    // 	permissionName: 'Employee Cost',
    // 	sortId: 2,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Cost Allocations',
    // 	sortId: 3,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Journals Entries',
    // 	sortId: 4,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeLogs',
    // 	sortId: 5,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeSheets',
    // 	sortId: 6,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Roles',
        sortId: 7,
        all: true,
        view: true,
        edit: true,
        delete: true,
        add: true,
    },
    {
        permissionName: 'Users',
        sortId: 8,
        all: true,
        view: true,
        edit: true,
        delete: true,
        add: true,
    },
    {
        permissionName: 'Integrations',
        sortId: 9,
        all: true,
        view: true,
        edit: true,
        delete: true,
        add: true,
    },
    // {
    // 	permissionName: 'Configurations',
    // 	sortId: 10,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Subscriptions',
        sortId: 11,
        all: true,
        view: true,
        edit: true,
        delete: true,
        add: true,
    },
    // {
    // 	permissionName: 'Custom Rules',
    // 	sortId: 12,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Time Summary',
    // 	sortId: 13,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Payroll Summary',
    // 	sortId: 14,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Customer Overview',
    // 	sortId: 15,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
];
exports.DefaultReadOnlyPermissions = [
    {
        permissionName: 'Dashboard',
        sortId: 1,
        all: false,
        view: true,
        edit: false,
        delete: false,
        add: false,
    },
    // {
    // 	permissionName: 'Employee Cost',
    // 	sortId: 2,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Cost Allocations',
    // 	sortId: 3,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Journals Entries',
    // 	sortId: 4,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeLogs',
    // 	sortId: 5,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeSheets',
    // 	sortId: 6,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Roles',
        sortId: 7,
        all: false,
        view: true,
        edit: false,
        delete: false,
        add: false,
    },
    {
        permissionName: 'Users',
        sortId: 8,
        all: false,
        view: true,
        edit: false,
        delete: false,
        add: false,
    },
    {
        permissionName: 'Integrations',
        sortId: 9,
        all: false,
        view: true,
        edit: false,
        delete: false,
        add: false,
    },
    // {
    // 	permissionName: 'Configurations',
    // 	sortId: 10,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Subscriptions',
        sortId: 11,
        all: false,
        view: true,
        edit: false,
        delete: false,
        add: false,
    },
    // {
    // 	permissionName: 'Custom Rules',
    // 	sortId: 12,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Time Summary',
    // 	sortId: 13,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Payroll Summary',
    // 	sortId: 14,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Customer Overview',
    // 	sortId: 15,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
];
exports.DefaultAccountantPermissions = [
    {
        permissionName: 'Dashboard',
        sortId: 1,
        all: false,
        view: true,
        edit: true,
        delete: false,
        add: true,
    },
    // {
    // 	permissionName: 'Employee Cost',
    // 	sortId: 2,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Cost Allocations',
    // 	sortId: 3,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Journals Entries',
    // 	sortId: 4,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeLogs',
    // 	sortId: 5,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'TimeSheets',
    // 	sortId: 6,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Roles',
        sortId: 7,
        all: false,
        view: true,
        edit: true,
        delete: false,
        add: true,
    },
    {
        permissionName: 'Users',
        sortId: 8,
        all: false,
        view: true,
        edit: true,
        delete: false,
        add: true,
    },
    {
        permissionName: 'Integrations',
        sortId: 9,
        all: false,
        view: true,
        edit: true,
        delete: false,
        add: true,
    },
    // {
    // 	permissionName: 'Configurations',
    // 	sortId: 10,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    {
        permissionName: 'Subscriptions',
        sortId: 11,
        all: false,
        view: true,
        edit: true,
        delete: false,
        add: true,
    },
    // {
    // 	permissionName: 'Custom Rules',
    // 	sortId: 12,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Time Summary',
    // 	sortId: 13,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Payroll Summary',
    // 	sortId: 14,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
    // {
    // 	permissionName: 'Customer Overview',
    // 	sortId: 15,
    // 	all: true,
    // 	view: true,
    // 	edit: true,
    // 	delete: true,
    // 	add: true,
    // },
];
